name: Trigger auto deployment for container-app-t55k65ad7zizu

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-t55k65ad7zizu-AutoDeployTrigger-747ff22a-fa2d-472e-80a4-efc2eb46eb8a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPT55K65AD7ZIZU_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPT55K65AD7ZIZU_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPT55K65AD7ZIZU_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPT55K65AD7ZIZU_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPT55K65AD7ZIZU_REGISTRY_PASSWORD }}
          containerAppName: container-app-t55k65ad7zizu
          resourceGroup: todonodejspgsqlgoogleautha08e88d9
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


